// app/layout.js
import localFont from "next/font/local";
import "./globals.css";
import VintageCursor from "@/components/Global/VintageMouse";

// Define the retro font
const retro = localFont({
  src: "./fonts/Retro.ttf",
  variable: "--font-retro",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Remove the style tag since we're using local font */}
      <body className={`${retro.variable} antialiased`}>
        {children}
        <VintageCursor />
      </body>
    </html>
  );
}
